[package]
name = "i2cwrite"
version = "0.2.0"
authors = ["Greg Brown <greg.brown.00@outlook.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[workspace]
members = ["i2cwrite-raspi"]

[dependencies]
embedded-hal = "0.2"

[dev-dependencies]
proptest = "0.9"
